// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: '1:398506827783:web:2cfddeba315d49f435caa2',
    messagingSenderId: '398506827783',
    projectId: 'angular-flutter-cloud',
    authDomain: 'angular-flutter-cloud.firebaseapp.com',
    storageBucket: 'angular-flutter-cloud.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:398506827783:android:fe4b03547d1b4c0135caa2',
    messagingSenderId: '398506827783',
    projectId: 'angular-flutter-cloud',
    storageBucket: 'angular-flutter-cloud.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:398506827783:ios:d235cc2e9501418c35caa2',
    messagingSenderId: '398506827783',
    projectId: 'angular-flutter-cloud',
    storageBucket: 'angular-flutter-cloud.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_API_KEY'] ?? '',
    appId: '1:398506827783:ios:d235cc2e9501418c35caa2',
    messagingSenderId: '398506827783',
    projectId: 'angular-flutter-cloud',
    storageBucket: 'angular-flutter-cloud.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY'] ?? '',
    appId: '1:398506827783:web:dbb9cfcf5517987735caa2',
    messagingSenderId: '398506827783',
    projectId: 'angular-flutter-cloud',
    authDomain: 'angular-flutter-cloud.firebaseapp.com',
    storageBucket: 'angular-flutter-cloud.firebasestorage.app',
  );
}
